# -*- coding: utf-8 -*-
"""XPE-RESOLUÇÃO-Pythonparaweb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12c1Jj2kI0sWoCtNXa3Qx2dgpTuiynHQ9
"""



import pandas as pd # Criação de um novo dicionário do Python onde o valor para cada chave é uma lista de mesmo tamanho.
#dados = { 'ano' : [ 2021, 2021, 2021, 2022, 2022], 'mês' : [ 'Outubro', 'Novembro', 'Dezembro', 'Janeiro', 'Fevereiro'],
#'volume' : [ 156.6, 96.8, 167.6, 378.6, 69.2] } # Um Dataframe está sendo criado a partir da lista criada anteriormente.
# E, diferente do exemplo da Série, # onde a chave havia se tornado o índice, aqui as chaves do dicionário se
# tornaram as colunas do Dataframe dframe = pd.DataFrame( dados )

import pandas as pd
tables = pd.read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")
# Assuming tables is already assigned correctly
earliest_date = tables[0]['Date added'].min()
print(earliest_date)  # Output the earliest date

tables[0]['Date added'].min()

"""Descobrindo que é a empresa mais antiga do S&P500...BK Bank of New York Mellon"""

import pandas as pd
tables = pd.read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")
tables[0]['Date added'].min()
# BK Bank of New York Mellon
tables[0]

print(type(tables))

print(type(tables[0]))

# Descobrir qual empresa com a data de fundação mais antiga

# vamos atribuir ela a um objeto, para começar a pesquisa
dfSP500 = tables[0]
dataFundacaoMaisAntigo = dfSP500['Founded'].min()

# Vamos imprimir este valor (ano) ?
dataFundacaoMaisAntigo

dfSP500[ dfSP500['Founded'] == dataFundacaoMaisAntigo ]

# Metodo que permite me ordenar os dados !! sort_values
dfSP500.sort_values( by = 'Founded', ascending = True)

# Metodo que permite me ordenar os dados !! sort_values, agora só com as 5 primeiras
dfSP500.sort_values( by = 'Founded', ascending = True).head(5)

# Metodo que permite me ordenar os dados !! sort_values, agora só com as 5 primeiras
dfSP500.sort_values( by = 'Founded', ascending = True).tail(5)

# importanto os dados de Cotação da empresa Telsa
import pandas as pd
dfTSLA = pd.read_csv('https://datasets-aulas.s3.amazonaws.com/dados+cota%C3%A7%C3%B5es/TSLA.csv');
dfTSLA

# aqui abaixo o indice é colocado automticamente de zero a...
dfTSLA.Close.plot()

dfTSLA.columns

# aqui abaixo o indice é colocado usando coluna data...
dfTSLA = dfTSLA.set_index('Date')
dfTSLA.Close.plot()

dfTSLA.dtypes

dfTSLA.count()

dfTSLA.describe()

import pandas as pd
dfPlayers = pd.read_csv('https://datasets-aulas.s3.amazonaws.com/Players.csv')
dfPlayers

"""---
### 📚 Exercício: Análise de informações dos jogadores da NBA ⛹️
Responda as seguintes questões a partir dos dados de jogadores da NBA [NBA Players stats since 1950](https://www.kaggle.com/datasets/drgilermo/nba-players-stats).

1. Qual a média de altura e de peso dos jogadores?
2. Crie uma nova coluna com o $IMC = \frac{peso}{altura²}$.
3. Qual jogador tem o maior IMC?
4. Qual jogador tem o menor IMC?
5. Qual a maior altura, o maior peso, a menor altura e o menor peso?
6. Em qual estado americano nasceu o maior número de jogadores?
7. Qual ou quais são os jogadores mais altos?

**Download**: [Players.csv](https://drive.google.com/file/d/1DuC5gbhvv_ZzFaebi9yuc0ZuuWaLBI9J/view?usp=sharing)
"""

# Responda as seguintes questões a partir dos dados de jogadores da NBA NBA Players stats since 1950.
# 1 - Qual a média de altura e de peso dos jogadores?
dfPlayers.describe()

dfPlayers.describe()[['height', 'weight']]

# Agora a media:

#dfPlayers.height.mean()
dfPlayers['height'].mean()

dfPlayers.height.mean()

#dfPlayers.height.mean()
dfPlayers['weight'].mean()

# 2 - Crie uma nova coluna com o IMC=peso.altura²

#exemplo
dfPlayers['nova_coluna'] = 'XP edu'
dfPlayers

# Calculando o IMC
dfPlayers['IMC'] = dfPlayers.weight / (dfPlayers.height / 100) ** 2
dfPlayers

"""3️⃣ Qual jogador tem o maior IMC?"""

# Sort.. ordenando pelo ascending ... maior resultado pegando os 5 head primeiros
dfPlayersMax = dfPlayers.sort_values(by=['IMC'], ascending=False).head(5)
dfPlayersMax

"""4️⃣ Qual jogador tem o menor IMC?"""

# Sort.. ordenando pelo ascending ... menor resultado pegando os 5 head primeiros
dfPlayersMin = dfPlayers.sort_values(by=['IMC'], ascending=True).head(5)
dfPlayersMin

dfPlayers[ dfPlayers['IMC'] == dfPlayers['IMC'].min() ]

dfPlayers[ dfPlayers['IMC'] == dfPlayers['IMC'].max() ]

"""6️⃣ Em qual estado americano nasceu o maior número de jogadores?"""

dfPlayers.groupby('birth_state')['Player'].count().sort_values(ascending=False)

"""Aqui está a explicação da expressão `dfPlayers.groupby('birth_state')['Player'].count().sort_values(ascending=False)` em português:

**1. `dfPlayers.groupby('birth_state')`:**

- Esta parte agrupa o DataFrame `dfPlayers` com base na coluna `'birth_state'`. Isso significa que o DataFrame será dividido em grupos, onde cada grupo contém linhas com o mesmo estado de nascimento.

**2. `['Player']`:**

- Dentro de cada grupo criado no passo anterior, esta expressão seleciona a coluna `'Player'`.

**3. `.count()`:**

- Para cada grupo (estado de nascimento), esta etapa conta o número de linhas (jogadores) naquele estado.

**4. `.sort_values(ascending=False)`:**

- Por fim, esta parte ordena os resultados da contagem (número de jogadores por estado de nascimento) em ordem decrescente. Isso significa que os estados com o maior número de jogadores aparecerão primeiro na saída.

**Resumo:**

Esta expressão calcula e classifica a contagem de jogadores por estado de nascimento no DataFrame `dfPlayers`. O resultado final é uma série que mostra o número de jogadores, ordenados do estado com o maior número de jogadores para o estado com o menor número de jogadores.
"""

# Observe aqui o value_Counts ja é mais simples ainda e funciona igual
dfPlayers.birth_state.value_counts()

7️⃣  Qual ou quais são os jogadores mais altos?

max_altura  = dfPlayers.height.max()
max_altura

dfPlayers[ dfPlayers.height == max_altura]

min_altura = dfPlayers.height.min()
min_altura

dfPlayers[ dfPlayers.height == min_altura]

# https://datasets-aulas.s3.amazonaws.com/dados+cota%C3%A7%C3%B5es/TSLA.csv

dfPlayers[ dfPlayers['IMC'] == dfPlayers['IMC'].min() ]
dfPlayers.groupby('birth_city')['Player'].count()

dfPlayersMinAltura = dfPlayers.sort_values(by=['height'], ascending=True).head(20)
dfPlayersMinAltura



